In [1]:
print("Hello")

Hello


In [2]:
x=[1,2,3,4,5]

In [3]:
import numpy as np
x=np.array([1,2,3,4,5])

In [4]:
print(x)

[1 2 3 4 5]


In [6]:
m=np.array([[1,5,2],
          [4,7,4],
          [2,0,9]])

In [7]:
print(m)

[[1 5 2]
 [4 7 4]
 [2 0 9]]


In [11]:
print('matrix Transpose:\n',m.transpose(),'\n')
print('matrix determinant:\n',np.linalg.det(m),'\n')
m_inv=np.linalg.inv(m)
print('matrix Inverse:\n',m_inv,'\n')
iden_m=np.dot(m,m_inv)
iden_m=np.round(np.abs(iden_m),0)
print('product of matrix and its inverse:\n',iden_m)

matrix Transpose:
 [[1 4 2]
 [5 7 0]
 [2 4 9]] 

matrix determinant:
 -105.00000000000006 

matrix Inverse:
 [[-0.6         0.42857143 -0.05714286]
 [ 0.26666667 -0.04761905 -0.03809524]
 [ 0.13333333 -0.0952381   0.12380952]] 

product of matrix and its inverse:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
eigen_vals,eigen_vecs=np.linalg.eig(m)
print('Eigen values','\n',eigen_vals,'\n')
print('Eigen vector','\n',eigen_vecs,'\n')

Eigen values 
 [-1.32455532 11.32455532  7.        ] 

Eigen vector 
 [[-0.91761521  0.46120352 -0.46829291]
 [ 0.35550789  0.79362022 -0.74926865]
 [ 0.17775394  0.39681011  0.46829291]] 



In [17]:
U,S,VT=np.linalg.svd(m)
print("getting svd outputs:\n")
print("U:\n",U,"\n")
print("S:\n",S,"\n")
print("VT:\n",VT,"\n")

getting svd outputs:

U:
 [[ 0.3831556  -0.39279153  0.83600634]
 [ 0.68811254 -0.48239977 -0.54202545]
 [ 0.61619228  0.78294653  0.0854506 ]] 

S:
 [12.10668383  6.91783499  1.25370079] 

VT:
 [[ 0.36079164  0.55610321  0.74871798]
 [-0.10935467 -0.7720271   0.62611158]
 [-0.92621323  0.30777163  0.21772844]] 



In [18]:
zeros_array=np.zeros((2,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
ones_array=np.ones((1,5),dtype=np.int32)
print(ones_array)

[[1 1 1 1 1]]


In [20]:
### ramdom variables

In [26]:
#descriptive statistics
import scipy as sp
import numpy as np

In [54]:
#get data
nums=np.random.randint(1,20,size=(1,15))[0]  #generate a 1_dimensional Numpy array containing 15 rand
print('Data:',nums)

Data: [ 3 16  1  8  2 19  1 12  8 15 16  6 19  3 18]


In [55]:
print('mean: ',np.mean(nums))
print('median: ',np.median(nums))

mean:  9.8
median:  8.0


In [56]:
from statistics import mode
r=mode(nums)
print(r)

3


In [59]:
print('Standerd Deviation: ',np.std(nums))
print('Variance: ',np.var(nums))
print('Skew: ',sp.stats.skew(nums))
print('Kurtosis: ',sp.stats.kurtosis(nums))

Standerd Deviation:  6.705221845696084
Variance:  44.96
Skew:  0.04505969202356173
Kurtosis:  -1.5897531692861036


In [61]:
#Exercise 1
#write a code to generate 3 ramdom integers between 100 and 999 which is divisible by 5

In [62]:
#Exercise 2
#write a code to generate 100 random lottery tickets and pick two lucky tickets from it as a winner.

#The lottery number must be 10 digits long.
#All 100 ticket number must be unique
#generate a random list of 1000 number using randrange() method to pick lucky 2 tickets.

In [ ]:
#Exercise 3
#Write a code to genarete a rondom password which meets